import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';import {resolve,dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)),home=resolve(here,'../../..');
const book='https://syeds-research-book.vercel.app/data/';
const src=(label,path,kind='json',note='Latest published reference file; source provenance remains unchanged.')=>({label,path,kind,note});
const common=[src('Theory catalogue','https://theoryscope.vercel.app/data/theories.json'),src('Scale catalogue','https://scalescope.vercel.app/data/scales.json')];
const configs=[
{slug:'research-suite',name:'Throughline',sources:common,description:'Check the published catalogues used across the research workflow.',manual:'Shared AI grounding has its own backend cache. Checking here does not regenerate AI outputs or invalidate that cache.'},
{slug:'researchflow',name:'ResearchFlow',pub:'public',sources:common,description:'Obtain latest published grounding references and fresh literature while preserving your proposal.',manual:'Backend catalogue grounding can remain cached for up to 24 hours. No generated stage is replaced by this panel.'},
{slug:'journaltime',name:'JournalTime',sources:[src('Journal catalogue','data.js','js')],description:'Check the published journal catalogue and fetch fresh paper metadata without touching your manuscript or uploaded file.',manual:'The journal catalogue is a maintained snapshot. Current Scopus status, fees and author instructions require official source checks.'},
{slug:'scholarscope',name:'ScholarScope',sources:[src('Publish catalogue','journals.js','js'),src('Journal Explorer catalogue','explorer/data/catalog.json')],description:'Refresh published journal references or search current literature. Existing OpenAlex discovery and Explorer’s journal-specific Crossref refresh remain available.',manual:'OpenAlex metrics are not Scopus verification. Explorer corpus counts and publisher calls update through separate reviewed releases.'},
{slug:'journal-timelines',name:'Journal Timelines',sources:[src('Registry and observed timings (8.5 MB)','data/journals.json'),src('Source manifest','data/source_manifest.json')],description:'Obtain the latest published registry and timing evidence. Your current filters remain intact.',manual:'The registry and article histories are built by the maintained source pipeline. Missing timing evidence remains unknown.'},
{slug:'theoryscope',name:'TheoryScope',pub:'public',sources:[src('Theory catalogue','data/theories.json'),src('Corpus mention evidence','data/corpus-usage.json')],description:'Fetch the latest published theory reference files and recent literature without changing your Canvas.',manual:'Theory additions require verified source review. Corpus mentions are machine matches, not validation or a live harvest.'},
{slug:'scalebase',name:'ScaleScope',entry:'client/index.html',pub:'client/public',sources:[src('Scale catalogue','data/scales.json'),src('Verbatim available items','data/scale-items.json'),src('Corpus usage','data/scale-usage.json')],description:'Check reference scales and item files without replacing your selected measures or reliability data.',manual:'Updated reference files must not silently alter a launched study. Adapted items are not newly validated scales.'},
{slug:'toolsscope',name:'ToolsScope',pub:'public',sources:[src('Scale reference catalogue','https://scalescope.vercel.app/data/scales.json')],description:'ToolsScope analyses use your local data. This panel obtains reference updates and current research metadata; it does not replace an uploaded dataset.',manual:'There is no automatic new participant dataset to fetch. Statistical engine changes arrive through app releases; independently reproduce final analyses.'},
{slug:'paperpulse',name:'PaperCards',pub:'public',sources:[src('Hand-coded corpus grounding summary',book+'corpus-snapshot.json'),src('Construct catalogue',book+'constructs.json')],description:'Check the published corpus references and search live literature without overwriting saved cards or running AI dissection.',manual:'AI extractions require paper-level checking. Existing Discover searches can fetch current provider results; saved libraries remain unchanged.'},
{slug:'syeds-research-book',name:'Research Book',sources:[src('Management corpus release','data/management/manifest.json'),src('Hand-coded corpus grounding summary','data/corpus-snapshot.json')],description:'Inspect the latest published corpus release and fetch fresh topic metadata without replacing hand-coded records.',manual:'A complete bulk snapshot requires the maintained harvest and audit pipeline. Live queries are bounded search results, not a complete corpus refresh.'},
{slug:'bookscope',name:'BookScope',sources:[src('Book catalogue','data/catalog.json'),src('Library summary','data/summary.json')],description:'Fetch the latest published book metadata while preserving your search and reading shelf.',manual:'New books, full texts, enrichment and the Pagefind search index require the licensed local extraction/rebuild pipeline. This panel does not obtain new PDFs.'},
{slug:'throughline-studio',name:'Throughline Studio',pub:'public',sources:[...common,src('Hand-coded corpus grounding summary',book+'corpus-snapshot.json')],description:'Obtain current published reference files and live paper metadata without changing your reading list, scales, locked protocol or manuscript.',manual:'Selected study measures and protocol versions remain frozen unless you deliberately amend them. Live provider metadata needs verification.'},
{slug:'throughline-cs',name:'Throughline CS',sources:[src('Published venue directory','venues.js','js')],description:'Check the maintained venue directory and search fresh article metadata while preserving experiments and writing.',manual:'Venue deadlines and current indexing require official checks. Existing arXiv, DBLP and other searches remain separate live sources.'},
{slug:'cadence',name:'Cadence',sources:[src('Scale reference catalogue','https://scalescope.vercel.app/data/scales.json')],description:'Inspect reference updates during study design. No launched survey item, response or participant progress is changed.',manual:'Freeze measures and scoring for launched studies. A newer catalogue is not permission to modify the ongoing instrument.'},
{slug:'fallacyscope',name:'FallacyScope',sources:[src('Published sourced field guide','pitfalls.js','js')],description:'Check the latest published guide and find recent literature on a research pitfall.',manual:'Curated entries require real canonical sources and a maintained release; the live search does not rewrite the guide.'}
];
let count=0;const script=readFileSync(join(here,'research-refresh.js'),'utf8');
for(const c of configs){const root=join(home,c.slug),entry=join(root,c.entry||'index.html'),pub=join(root,c.pub||'');if(!existsSync(entry))throw Error('Missing entry '+entry);mkdirSync(pub,{recursive:true});writeFileSync(join(pub,'research-refresh.js'),script);let html=readFileSync(entry,'utf8');const config={...c};delete config.entry;delete config.pub;const attrs=JSON.stringify(config).replace(/&/g,'&amp;').replace(/'/g,'&#39;').replace(/</g,'&lt;');const source=c.pub?'/research-refresh.js':'research-refresh.js';const block=`<!-- RESEARCH-REFRESH:START -->\n<script defer src="${source}" data-config='${attrs}'></script>\n<!-- RESEARCH-REFRESH:END -->`;
html=html.replace(/<!-- RESEARCH-REFRESH:START -->[\s\S]*?<!-- RESEARCH-REFRESH:END -->\s*/g,'');html=html.replace('</head>',block+'\n</head>');writeFileSync(entry,html);count++;
if(c.slug==='scholarscope'){const file=join(root,'explorer/index.html');let text=readFileSync(file,'utf8').replace(/<!-- RESEARCH-REFRESH:START -->[\s\S]*?<!-- RESEARCH-REFRESH:END -->\s*/g,'');text=text.replace('</head>',block.replace('src="research-refresh.js"','src="../research-refresh.js"')+'\n</head>');writeFileSync(file,text);count++;}}
console.log(`Installed safe latest-data panel in ${count} entry points across ${configs.length} projects.`);
