/* Generated copies: edit this file and catalog.json, then run build.mjs. */
(()=>{'use strict';
 const catalog=/*CATALOG*/[];
 const home='https://syahmedu.github.io/research-suite/';
 const style=`:host{display:block;position:relative;z-index:110;color:#211c2c;font:14px/1.5 system-ui,sans-serif}*{box-sizing:border-box}a{color:inherit;text-decoration:none}a:hover{text-decoration:underline}a:focus-visible,summary:focus-visible{outline:3px solid #8154cf;outline-offset:3px}.bar{display:flex;gap:16px;align-items:center;flex-wrap:wrap;background:#f6f1e8;padding:10px max(16px,calc((100% - 1160px)/2));border-bottom:1px solid #ded8cf}.bar>a{min-height:28px;display:flex;align-items:center;font-weight:600}.bar details{margin-left:auto}.bar summary{cursor:pointer;padding:5px}.menu{position:absolute;left:16px;right:16px;z-index:100000;background:#fff;border:1px solid #ddd;border-radius:14px;padding:22px;box-shadow:0 15px 50px #0003;max-height:75vh;overflow:auto}.group{margin:0 0 24px}.group h3{font-size:13px;text-transform:uppercase;letter-spacing:.06em;color:#625377;margin:0 0 10px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.card{display:block;border:1px solid #ded8cf;border-radius:12px;padding:16px;background:#fff}.card strong{display:block;font-size:17px;margin-bottom:6px}.card p{font-size:14px;color:#574f62;margin:0}.note{font-size:13px;color:#665d70}.directory{padding:26px;background:#f6f1e8;border-radius:18px}.directory h2{font:600 30px/1.2 Georgia,serif;margin:0 0 12px}.directory>p{max-width:780px}.menu .card{padding:12px}.menu .card p{display:none}@media(max-width:500px){.bar{gap:10px;font-size:12px}.bar details{margin-left:0}.directory{padding:18px}.cards{grid-template-columns:1fr}}@media print{.bar{display:none}}`;
 function el(tag,text){const e=document.createElement(tag);if(text)e.textContent=text;return e;}
 function link(name,url){const a=el('a',name);a.href=url;return a;}
 function groups(parent){for(const group of [...new Set(catalog.map(x=>x.group))]){const section=el('section');section.className='group';section.append(el('h3',group));const grid=el('div');grid.className='cards';for(const item of catalog.filter(x=>x.group===group)){const a=link('',item.url);a.className='card';a.append(el('strong',item.name+' ↗'),el('p',item.description));grid.append(a);}section.append(grid);parent.append(section);}}
 class ResearchNavigation extends HTMLElement{connectedCallback(){if(this.shadowRoot)return;const root=this.attachShadow({mode:'open'});root.append(el('style',style));const nav=el('nav');nav.className='bar';nav.setAttribute('aria-label','Research navigation');nav.append(link('Research home',home),link('My papers','https://syed-papers.vercel.app/'),link('Studio','https://throughline-studio.vercel.app/'));const more=el('details');more.append(el('summary','All research ▾'));const menu=el('div');menu.className='menu';groups(menu);menu.append(el('p','Links open each existing workspace. Saved work follows only the handoffs each tool supports.'));more.append(menu);nav.append(more);root.append(nav);root.addEventListener('keydown',e=>{if(e.key==='Escape'){more.open=false;more.querySelector('summary').focus();}});document.addEventListener('click',e=>{if(!e.composedPath().includes(this))more.open=false;});}}
 class ResearchDirectory extends HTMLElement{connectedCallback(){if(this.shadowRoot)return;const root=this.attachShadow({mode:'open'});root.append(el('style',style));const box=el('section');box.className='directory';box.append(el('h2','All your research, connected.'),el('p','Resume one of your 22 papers, work through its stages in Studio, and reach every research library and companion from here. Research Kitchen is inside Studio → Analyze.'));groups(box);const note=el('p','The papers desk carries a copy of a selected paper’s source documents into Studio. Independent apps and Solo Publish keep their own saved work; links do not automatically merge those records.');note.className='note';box.append(note);root.append(box);}}
 customElements.define('research-navigation',ResearchNavigation);customElements.define('research-directory',ResearchDirectory);
 if(!document.querySelector('research-navigation'))document.body.prepend(el('research-navigation'));
})();
